// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZGa0uysMZ45TAeXwc7iaH9MNYxZNp9GI',
    appId: '1:103500859296:web:59b3618469ebc619ecc6c5',
    messagingSenderId: '103500859296',
    projectId: 'watsappclone-5f247',
    authDomain: 'watsappclone-5f247.firebaseapp.com',
    storageBucket: 'watsappclone-5f247.appspot.com',
    measurementId: 'G-RRJGWW0B1Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLVCGc82_0HZ2bXi2F1xQkIUKefYbolek',
    appId: '1:103500859296:android:95c88011b3b7019eecc6c5',
    messagingSenderId: '103500859296',
    projectId: 'watsappclone-5f247',
    storageBucket: 'watsappclone-5f247.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqmSrPsKzX-m-_ERxzLbXp1DiFCa8BgaE',
    appId: '1:103500859296:ios:d99ad3652531cf91ecc6c5',
    messagingSenderId: '103500859296',
    projectId: 'watsappclone-5f247',
    storageBucket: 'watsappclone-5f247.appspot.com',
    iosBundleId: 'com.example.watsapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqmSrPsKzX-m-_ERxzLbXp1DiFCa8BgaE',
    appId: '1:103500859296:ios:d4f0bee763cd8c29ecc6c5',
    messagingSenderId: '103500859296',
    projectId: 'watsappclone-5f247',
    storageBucket: 'watsappclone-5f247.appspot.com',
    iosBundleId: 'com.example.watsapp.RunnerTests',
  );
}
